default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DATABASE_PORT', 3306) %>
  username: <%= ENV.fetch('DATABASE_USER', 'root') %>
  password: <%= ENV.fetch('DATABASE_PASS', '') %>

development:
  <<: *default
  database: barong_development

test:
  <<: *default
  database: barong_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
